export interface PhoneCountry {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  minDigits: number;
  maxDigits: number;
  groups?: number[];
}

export const SHOW_SEND = true; // Временно скрываем форму отправки, так как бэкенд еще не готов

export const MAX_FILES = 5;
export const MAX_FILE_SIZE = 10 * 1024 * 1024;

export const PERSONAL_DATA_OPERATOR = {
  name: "ИП Вагизов Алмаз Фаридович",
  email: "copy@9v.ru",
  address:
    "427740, Удмуртская Республика, р-н Граховский, д. Яги-Какси, ул. Октябрьская, д. 43",
  phone: "8 (843) 525-00-00",
};

export const PERSONAL_DATA_POLICY_SECTIONS = [
  {
    title: "1. Общие положения",
    paragraphs: [
      `Настоящая политика применяется к персональным данным, которые пользователь предоставляет при отправке расчета через форму на сайте ${PERSONAL_DATA_OPERATOR.name}.`,
      `Оператор персональных данных: ${PERSONAL_DATA_OPERATOR.name}, email: ${PERSONAL_DATA_OPERATOR.email}, адрес: ${PERSONAL_DATA_OPERATOR.address}, тел.: ${PERSONAL_DATA_OPERATOR.phone}.`,
      "Оператор обрабатывает персональные данные в соответствии с законодательством Российской Федерации и только в объеме, необходимом для обработки обращения пользователя.",
    ],
  },
  {
    title: "2. Состав персональных данных",
    paragraphs: [
      "Оператор может обрабатывать имя или наименование компании, номер телефона, адрес электронной почты, текст комментария и прикрепленные пользователем файлы.",
      "Сведения из формы расчета используются только в связке с обращением пользователя и необходимы для подготовки ответа.",
    ],
  },
  {
    title: "3. Цели обработки",
    paragraphs: [
      "Подготовка и отправка расчета, обратная связь с пользователем, уточнение деталей запроса, обработка приложенных материалов и ведение переписки по обращению.",
    ],
  },
  {
    title: "4. Правовые основания",
    paragraphs: [
      "Основанием обработки является согласие пользователя, выраженное путем проставления чекбокса перед отправкой формы.",
    ],
  },
  {
    title: "5. Условия обработки и хранения",
    paragraphs: [
      "Персональные данные обрабатываются с использованием средств автоматизации и без них, с применением необходимых организационных и технических мер защиты.",
      "Данные хранятся не дольше, чем это требуется для обработки обращения и дальнейшего взаимодействия по нему, если иной срок не предусмотрен законодательством Российской Федерации.",
    ],
  },
  {
    title: "6. Права пользователя",
    paragraphs: [
      `Пользователь вправе запросить уточнение, обновление, блокирование или удаление своих персональных данных, а также отозвать согласие на их обработку, направив обращение оператору по адресу ${PERSONAL_DATA_OPERATOR.email} или по адресу: ${PERSONAL_DATA_OPERATOR.address}.`,
    ],
  },
];

const CIS_PRIORITY_CODES = [
  "RU",
  "BY",
  "KZ",
  "AZ",
  "AM",
  "KG",
  "MD",
  "TJ",
  "TM",
  "UZ",
] as const;

export const PHONE_COUNTRIES: PhoneCountry[] = [
  {
    code: "RU",
    name: "Россия",
    dialCode: "7",
    flag: "🇷🇺",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 2, 2],
  },
  {
    code: "BY",
    name: "Беларусь",
    dialCode: "375",
    flag: "🇧🇾",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "KZ",
    name: "Казахстан",
    dialCode: "7",
    flag: "🇰🇿",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 2, 2],
  },
  {
    code: "AZ",
    name: "Азербайджан",
    dialCode: "994",
    flag: "🇦🇿",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "AM",
    name: "Армения",
    dialCode: "374",
    flag: "🇦🇲",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "KG",
    name: "Кыргызстан",
    dialCode: "996",
    flag: "🇰🇬",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "MD",
    name: "Молдова",
    dialCode: "373",
    flag: "🇲🇩",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "TJ",
    name: "Таджикистан",
    dialCode: "992",
    flag: "🇹🇯",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "TM",
    name: "Туркменистан",
    dialCode: "993",
    flag: "🇹🇲",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "UZ",
    name: "Узбекистан",
    dialCode: "998",
    flag: "🇺🇿",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "AU",
    name: "Австралия",
    dialCode: "61",
    flag: "🇦🇺",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "AT",
    name: "Австрия",
    dialCode: "43",
    flag: "🇦🇹",
    minDigits: 7,
    maxDigits: 13,
  },
  {
    code: "AL",
    name: "Албания",
    dialCode: "355",
    flag: "🇦🇱",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "DZ",
    name: "Алжир",
    dialCode: "213",
    flag: "🇩🇿",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "AR",
    name: "Аргентина",
    dialCode: "54",
    flag: "🇦🇷",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "BE",
    name: "Бельгия",
    dialCode: "32",
    flag: "🇧🇪",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "BG",
    name: "Болгария",
    dialCode: "359",
    flag: "🇧🇬",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "BR",
    name: "Бразилия",
    dialCode: "55",
    flag: "🇧🇷",
    minDigits: 10,
    maxDigits: 11,
    groups: [2, 5, 4],
  },
  {
    code: "GB",
    name: "Великобритания",
    dialCode: "44",
    flag: "🇬🇧",
    minDigits: 10,
    maxDigits: 10,
    groups: [4, 3, 3],
  },
  {
    code: "HU",
    name: "Венгрия",
    dialCode: "36",
    flag: "🇭🇺",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "VN",
    name: "Вьетнам",
    dialCode: "84",
    flag: "🇻🇳",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "DE",
    name: "Германия",
    dialCode: "49",
    flag: "🇩🇪",
    minDigits: 10,
    maxDigits: 11,
  },
  {
    code: "GR",
    name: "Греция",
    dialCode: "30",
    flag: "🇬🇷",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "GE",
    name: "Грузия",
    dialCode: "995",
    flag: "🇬🇪",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "DK",
    name: "Дания",
    dialCode: "45",
    flag: "🇩🇰",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 2, 2, 2],
  },
  {
    code: "EG",
    name: "Египет",
    dialCode: "20",
    flag: "🇪🇬",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "IL",
    name: "Израиль",
    dialCode: "972",
    flag: "🇮🇱",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "IN",
    name: "Индия",
    dialCode: "91",
    flag: "🇮🇳",
    minDigits: 10,
    maxDigits: 10,
    groups: [5, 5],
  },
  {
    code: "ID",
    name: "Индонезия",
    dialCode: "62",
    flag: "🇮🇩",
    minDigits: 9,
    maxDigits: 11,
  },
  {
    code: "IE",
    name: "Ирландия",
    dialCode: "353",
    flag: "🇮🇪",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 4],
  },
  {
    code: "ES",
    name: "Испания",
    dialCode: "34",
    flag: "🇪🇸",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "IT",
    name: "Италия",
    dialCode: "39",
    flag: "🇮🇹",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "CA",
    name: "Канада",
    dialCode: "1",
    flag: "🇨🇦",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "CY",
    name: "Кипр",
    dialCode: "357",
    flag: "🇨🇾",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "CN",
    name: "Китай",
    dialCode: "86",
    flag: "🇨🇳",
    minDigits: 11,
    maxDigits: 11,
    groups: [3, 4, 4],
  },
  {
    code: "LV",
    name: "Латвия",
    dialCode: "371",
    flag: "🇱🇻",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "LT",
    name: "Литва",
    dialCode: "370",
    flag: "🇱🇹",
    minDigits: 8,
    maxDigits: 8,
    groups: [3, 2, 3],
  },
  {
    code: "MY",
    name: "Малайзия",
    dialCode: "60",
    flag: "🇲🇾",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "MX",
    name: "Мексика",
    dialCode: "52",
    flag: "🇲🇽",
    minDigits: 10,
    maxDigits: 10,
    groups: [2, 4, 4],
  },
  {
    code: "AE",
    name: "ОАЭ",
    dialCode: "971",
    flag: "🇦🇪",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 4],
  },
  {
    code: "NO",
    name: "Норвегия",
    dialCode: "47",
    flag: "🇳🇴",
    minDigits: 8,
    maxDigits: 8,
    groups: [3, 2, 3],
  },
  {
    code: "PL",
    name: "Польша",
    dialCode: "48",
    flag: "🇵🇱",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "PT",
    name: "Португалия",
    dialCode: "351",
    flag: "🇵🇹",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "RO",
    name: "Румыния",
    dialCode: "40",
    flag: "🇷🇴",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "RS",
    name: "Сербия",
    dialCode: "381",
    flag: "🇷🇸",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "SG",
    name: "Сингапур",
    dialCode: "65",
    flag: "🇸🇬",
    minDigits: 8,
    maxDigits: 8,
    groups: [4, 4],
  },
  {
    code: "SK",
    name: "Словакия",
    dialCode: "421",
    flag: "🇸🇰",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "SI",
    name: "Словения",
    dialCode: "386",
    flag: "🇸🇮",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "US",
    name: "США",
    dialCode: "1",
    flag: "🇺🇸",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "TH",
    name: "Таиланд",
    dialCode: "66",
    flag: "🇹🇭",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 4],
  },
  {
    code: "TR",
    name: "Турция",
    dialCode: "90",
    flag: "🇹🇷",
    minDigits: 10,
    maxDigits: 10,
    groups: [3, 3, 4],
  },
  {
    code: "FI",
    name: "Финляндия",
    dialCode: "358",
    flag: "🇫🇮",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "FR",
    name: "Франция",
    dialCode: "33",
    flag: "🇫🇷",
    minDigits: 9,
    maxDigits: 9,
    groups: [1, 2, 2, 2, 2],
  },
  {
    code: "HR",
    name: "Хорватия",
    dialCode: "385",
    flag: "🇭🇷",
    minDigits: 8,
    maxDigits: 9,
  },
  {
    code: "ME",
    name: "Черногория",
    dialCode: "382",
    flag: "🇲🇪",
    minDigits: 8,
    maxDigits: 8,
    groups: [2, 3, 3],
  },
  {
    code: "CZ",
    name: "Чехия",
    dialCode: "420",
    flag: "🇨🇿",
    minDigits: 9,
    maxDigits: 9,
    groups: [3, 3, 3],
  },
  {
    code: "CH",
    name: "Швейцария",
    dialCode: "41",
    flag: "🇨🇭",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "SE",
    name: "Швеция",
    dialCode: "46",
    flag: "🇸🇪",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 2, 2],
  },
  {
    code: "EE",
    name: "Эстония",
    dialCode: "372",
    flag: "🇪🇪",
    minDigits: 7,
    maxDigits: 8,
  },
  {
    code: "ZA",
    name: "ЮАР",
    dialCode: "27",
    flag: "🇿🇦",
    minDigits: 9,
    maxDigits: 9,
    groups: [2, 3, 4],
  },
  {
    code: "KR",
    name: "Южная Корея",
    dialCode: "82",
    flag: "🇰🇷",
    minDigits: 9,
    maxDigits: 10,
  },
  {
    code: "JP",
    name: "Япония",
    dialCode: "81",
    flag: "🇯🇵",
    minDigits: 10,
    maxDigits: 10,
    groups: [2, 4, 4],
  },
];

export const PHONE_COUNTRIES_BY_CODE = new Map(
  PHONE_COUNTRIES.map((country) => [country.code, country]),
);

export const SORTED_PHONE_COUNTRIES = [...PHONE_COUNTRIES].sort(
  (left, right) => {
    const leftPriority = CIS_PRIORITY_CODES.indexOf(
      left.code as (typeof CIS_PRIORITY_CODES)[number],
    );
    const rightPriority = CIS_PRIORITY_CODES.indexOf(
      right.code as (typeof CIS_PRIORITY_CODES)[number],
    );

    if (leftPriority !== -1 || rightPriority !== -1) {
      if (leftPriority === -1) return 1;
      if (rightPriority === -1) return -1;
      return leftPriority - rightPriority;
    }

    return left.name.localeCompare(right.name, "ru");
  },
);
